"""Checkout inventory and analysis render from the org-ecosystem registry."""

from __future__ import annotations

import argparse
import json
import os
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

from domain.bootstrap import MARKER_FILES, find_repo
from domain.model import DEFERRED_STACKS, Registry, Repo, load_registry

HUB_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS_PATH = HUB_ROOT / "analysis" / "repository_analysis.md"
GENERATED_MARKER = (
    "Generated by `python3 -m domain.inventory --write-analysis`. "
    "Do not hand-edit sibling rows."
)
OBSERVED_FILES = (
    "package.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "package-lock.json",
    "pyproject.toml",
    "requirements.txt",
    "Project.toml",
    "composer.json",
    "README.md",
    "README",
    "pom.xml",
)
INSTALL_LOCKFILES = (
    "pnpm-lock.yaml",
    "yarn.lock",
    "package-lock.json",
    "requirements.txt",
    "pyproject.toml",
)
RETIRED_WORKSPACE_NAMES = ("business-directory-template", "bus-listing")
OUT_OF_SNAPSHOT_EXAMPLES = (
    "business-directory-template",
    "bus-listing",
    "paperclip",
)


@dataclass(frozen=True)
class SiblingStatus:
    name: str
    role: str
    install_kind: str
    stack: str
    directory: str | None
    discoverable: bool
    observed: tuple[str, ...]
    missing_kind_files: tuple[str, ...]
    installable_checkout_only: bool

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["observed"] = list(self.observed)
        data["missing_kind_files"] = list(self.missing_kind_files)
        return data


@dataclass(frozen=True)
class InventoryReport:
    hub_name: str
    hub_directory: str | None
    siblings: tuple[SiblingStatus, ...]
    unregistered: tuple[str, ...]

    @property
    def missing_discoverable(self) -> tuple[str, ...]:
        return tuple(item.name for item in self.siblings if not item.discoverable)

    @property
    def unmarked_directories(self) -> tuple[str, ...]:
        return tuple(
            item.name
            for item in self.siblings
            if item.directory is not None and not item.discoverable
        )

    @property
    def kind_drift(self) -> tuple[str, ...]:
        return tuple(
            item.name
            for item in self.siblings
            if item.discoverable and item.missing_kind_files
        )

    @property
    def checkout_only_installable(self) -> tuple[str, ...]:
        return tuple(item.name for item in self.siblings if item.installable_checkout_only)

    def as_dict(self) -> dict[str, Any]:
        return {
            "hubName": self.hub_name,
            "hubDirectory": self.hub_directory,
            "siblings": [item.as_dict() for item in self.siblings],
            "unregistered": list(self.unregistered),
            "missingDiscoverable": list(self.missing_discoverable),
            "unmarkedDirectories": list(self.unmarked_directories),
            "kindDrift": list(self.kind_drift),
            "checkoutOnlyInstallable": list(self.checkout_only_installable),
        }


def search_roots(registry: Registry) -> tuple[str, ...]:
    override = os.environ.get("CLOUD_AGENT_REPO_ROOTS")
    if override is not None:
        return tuple(part for part in override.split(":") if part)
    return registry.search_roots


def locate_directory(name: str, registry: Registry) -> Path | None:
    for raw in search_roots(registry):
        directory = Path(raw) / name
        if directory.is_dir():
            return directory
    return None


def observed_files(directory: Path) -> tuple[str, ...]:
    found = [name for name in OBSERVED_FILES if (directory / name).exists()]
    return tuple(found)


def expected_kind_files(repo: Repo) -> tuple[str, ...]:
    kind = repo.install_kind
    if kind == "pnpm":
        return ("package.json", "pnpm-lock.yaml")
    if kind == "yarn":
        return ("package.json", "yarn.lock")
    if kind == "npm":
        return ("package.json", "package-lock.json")
    if kind == "python-editable":
        return ("pyproject.toml",)
    if kind == "python-requirements":
        return (repo.requirements_file or "requirements.txt",)
    if kind == "python-packages":
        return repo.editable_packages or ("./packages",)
    if kind == "presence-only":
        return ("README.md",)
    return ()


def missing_kind_files(repo: Repo, directory: Path | None, discoverable: bool) -> tuple[str, ...]:
    if not discoverable or directory is None or repo.install_kind == "none":
        return ()
    missing: list[str] = []
    for rel in expected_kind_files(repo):
        target = directory / rel
        if not target.exists():
            missing.append(rel)
    return tuple(missing)


def is_installable_checkout_only(repo: Repo, observed: Iterable[str]) -> bool:
    if not repo.is_checkout_only():
        return False
    return any(name in observed for name in INSTALL_LOCKFILES)


def build_inventory(registry: Registry | None = None) -> InventoryReport:
    loaded = registry or load_registry()
    hub_dir = locate_directory(loaded.hub.name, loaded)
    siblings: list[SiblingStatus] = []
    named = {loaded.hub.name, *(repo.name for repo in loaded.repos)}
    for repo in loaded.repos:
        directory = locate_directory(repo.name, loaded)
        discovered = find_repo(repo.name, loaded)
        observed = observed_files(directory) if directory is not None else ()
        siblings.append(
            SiblingStatus(
                name=repo.name,
                role=repo.role,
                install_kind=repo.install_kind,
                stack=repo.stack,
                directory=str(directory) if directory is not None else None,
                discoverable=discovered is not None,
                observed=observed,
                missing_kind_files=missing_kind_files(
                    repo, directory, discovered is not None
                ),
                installable_checkout_only=is_installable_checkout_only(repo, observed),
            )
        )
    unregistered: list[str] = []
    for raw in search_roots(loaded):
        root = Path(raw)
        if not root.is_dir():
            continue
        for child in sorted(root.iterdir()):
            if not child.is_dir() or child.name.startswith(".") or child.name in named:
                continue
            if any((child / marker).is_file() for marker in MARKER_FILES):
                unregistered.append(child.name)
    return InventoryReport(
        hub_name=loaded.hub.name,
        hub_directory=str(hub_dir) if hub_dir is not None else None,
        siblings=tuple(siblings),
        unregistered=tuple(unregistered),
    )


def _md_table(headers: tuple[str, ...], rows: Iterable[tuple[str, ...]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _note(repo: Repo) -> str:
    bits: list[str] = []
    if repo.presence_note:
        bits.append(repo.presence_note)
    if repo.editable_spec:
        bits.append(f"`-e {repo.editable_spec}`")
    if repo.requirements_file:
        bits.append(repo.requirements_file)
    if repo.editable_packages:
        bits.append(" ".join(repo.editable_packages))
    if repo.packages:
        bits.append("packages: " + ", ".join(repo.packages))
    if repo.constraints:
        bits.append(", ".join(repo.constraints))
    return "; ".join(bits) if bits else "—"


def render_repository_analysis(registry: Registry | None = None) -> str:
    loaded = registry or load_registry()
    cores = loaded.cpu_core()
    checkout = loaded.checkout_only()
    deferred = tuple(repo for repo in checkout if repo.stack in DEFERRED_STACKS)
    later_track = tuple(
        repo
        for repo in checkout
        if repo.stack in {"node", "python"}
    )
    docs_mixed = tuple(repo for repo in checkout if repo.stack in {"docs", "mixed"})
    core_rows = tuple(
        (
            repo.name,
            repo.install_kind,
            repo.stack,
            str(repo.install_order),
            _note(repo),
        )
        for repo in cores
    )
    checkout_rows = tuple(
        (
            repo.name,
            repo.stack,
            "deferred toolchain" if repo.stack in DEFERRED_STACKS else "not default-installed",
        )
        for repo in checkout
    )
    return "\n".join(
        [
            "# SkinTwin-AI Repository Analysis",
            "",
            GENERATED_MARKER,
            "",
            "Canonical identity is [`domain/org-ecosystem.json`](../domain/org-ecosystem.json). "
            "This page is the inventory projection of that registry. "
            "Live checkout presence and kind-marker drift are printed by "
            "`python3 -m domain.inventory`, not frozen here.",
            "",
            "## Cloud Agent snapshot",
            "",
            f"- Hub: `{loaded.hub.name}` (not a `repositoryDependencies` entry).",
            f"- Siblings: {len(loaded.repos)}.",
            f"- CPU-core: {len(cores)}.",
            f"- Checkout-only: {len(checkout)}.",
            f"- Deferred GPU/Julia/PHP: {len(deferred)} (never default-installed).",
            f"- Node/Python checkout-only: {len(later_track)} (later install track only).",
            f"- Docs/mixed checkout-only: {len(docs_mixed)}.",
            "",
            "Listing a sibling in `repositoryDependencies` grants GitHub token scope. "
            "It does not install that tree.",
            "",
            "## Hub",
            "",
            _md_table(
                ("Field", "Value"),
                (
                    ("name", loaded.hub.name),
                    ("org", loaded.hub.org),
                    ("environment", loaded.hub.environment_name),
                    ("install", loaded.hub.install),
                    ("role", "hub"),
                ),
            ),
            "",
            "## CPU-core",
            "",
            "Default Cloud Agent install targets when the checkout is present. "
            "Skip-missing still applies.",
            "",
            _md_table(
                ("Repository", "Install kind", "Stack", "Order", "Notes"),
                core_rows,
            ),
            "",
            "## Checkout-only",
            "",
            "Present trees may have lockfiles. Install still ignores them.",
            "",
            _md_table(
                ("Repository", "Stack", "Install track"),
                checkout_rows,
            ),
            "",
            "## Discovery markers",
            "",
            "`find_repo` treats a sibling as present only when a search-root "
            f"directory contains one of `{', '.join(MARKER_FILES)}`. "
            "Autotools trees that ship `README` without `README.md` can exist on disk "
            "and still be undiscoverable. That is inventory drift, not an install failure.",
            "",
            "## Outside this Cloud Agent snapshot",
            "",
            "The GitHub org is wider than `repositoryDependencies`. These names are "
            "**not** current workspace siblings and must not re-enter the inventory table "
            "without an explicit hub edit that expands token scope:",
            "",
            *(f"- `{name}`" for name in OUT_OF_SNAPSHOT_EXAMPLES),
            "",
            f"Retired-from-snapshot aliases still seen in older docs: "
            f"{', '.join(f'`{name}`' for name in RETIRED_WORKSPACE_NAMES)}. "
            "The in-snapshot directory product is `skincare-directory`.",
            "",
            "## Later tracks (not this increment)",
            "",
            "- GPU/Julia/PHP default install remains forbidden.",
            "- Secret-backed `start`/`terminals` remain omitted.",
            "- Promoting a checkout-only Node/Python sibling into CPU-core requires a "
            "later install-track plan; observed lockfiles alone are not a role change.",
            "",
            "## Prior design notes",
            "",
            "These concepts remain descriptive. They are not a second sibling list.",
            "",
            "### Cognitive layer",
            "",
            "- `skintwin`: Alchemist Engine specification.",
            "- `skintwin-asi`: Dual-hemisphere cognitive architecture.",
            "- `multiskin`: Multiscale biological modeling (checkout-only GPU).",
            "",
            "### Business and integration layer",
            "",
            "- `skintwin-customer-portal`: Multi-tenant business management (CPU-core).",
            "- `regima-training-lms`: LMS (checkout-only Node).",
            "- `skintwin-integrations`: External platform connectors (CPU-core).",
            "- `org-skin`: Organization GitHub SDK (CPU-core).",
            "",
            "### Shared concepts",
            "",
            "- Cognitive agents: Deep Tree Echo, Marduk, CEO (JAX).",
            "- Shared entities: client, appointment, product, organization/tenant.",
            "- Integration patterns: webhooks, REST/GraphQL, event-driven sync.",
            "- External systems: Shopify, Wix, OpenCart, Stripe/PayStack, "
            "QuickBooks/Xero, ERPNext, WorkOS, xAPI/SCORM/LTI.",
            "",
        ]
    )


def analysis_is_current(path: Path | None = None, registry: Registry | None = None) -> bool:
    target = path or ANALYSIS_PATH
    return target.read_text() == render_repository_analysis(registry)


def write_analysis(path: Path | None = None, registry: Registry | None = None) -> Path:
    target = path or ANALYSIS_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_repository_analysis(registry))
    return target


def _supply_chain_lines() -> list[str]:
    from domain.supply_chain import load_stages

    lines = ["supply chain:"]
    for stage in load_stages():
        recorded_by = stage.surface_owner or stage.owner
        lines.append(f"  {stage.id}: {stage.owner} recorded by {recorded_by}/{stage.surface}")
    from domain.metagraph import load_document

    document = load_document()
    lines.append(
        "metagraph: "
        + ", ".join(f"{fiber.stage}->{fiber.type_id}" for fiber in document.fibers)
    )
    return lines


def format_report(report: InventoryReport) -> str:
    lines = [
        f"hub: {report.hub_name}"
        + (f" @ {report.hub_directory}" if report.hub_directory else " (directory not in search roots)"),
        f"siblings: {len(report.siblings)}",
        f"discoverable: {sum(1 for item in report.siblings if item.discoverable)}",
        f"unmarked directories: {', '.join(report.unmarked_directories) or 'none'}",
        f"missing discoverable: {', '.join(report.missing_discoverable) or 'none'}",
        f"cpu-core kind drift: {', '.join(report.kind_drift) or 'none'}",
        f"checkout-only with install markers: {', '.join(report.checkout_only_installable) or 'none'}",
        f"unregistered: {', '.join(report.unregistered) or 'none'}",
        *_supply_chain_lines(),
        "",
        _md_table(
            ("Repository", "Role", "Kind", "Discoverable", "Kind drift", "Observed"),
            tuple(
                (
                    item.name,
                    item.role,
                    item.install_kind,
                    "yes" if item.discoverable else "no",
                    ",".join(item.missing_kind_files) or "—",
                    ",".join(item.observed) or "—",
                )
                for item in report.siblings
            ),
        ),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inventory Cloud Agent siblings from domain/org-ecosystem.json."
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the live checkout report as JSON.",
    )
    parser.add_argument(
        "--write-analysis",
        action="store_true",
        help=f"Rewrite {ANALYSIS_PATH.relative_to(HUB_ROOT)} from the registry.",
    )
    parser.add_argument(
        "--check-analysis",
        action="store_true",
        help="Exit 1 if the committed analysis is not the registry render.",
    )
    args = parser.parse_args(argv)
    registry = load_registry()
    if args.write_analysis:
        write_analysis(registry=registry)
    if args.check_analysis and not analysis_is_current(registry=registry):
        print("analysis/repository_analysis.md is stale; run --write-analysis", flush=True)
        return 1
    report = build_inventory(registry)
    if args.json:
        print(json.dumps(report.as_dict(), indent=2))
    else:
        print(format_report(report), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
